# Server
server.port=8080
spring.application.name=Pocket_Health

# PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pocket_health
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=Pocket_Health_spring_secret_key_2026_must_be_256bits_long
app.jwt.expiration=604800000

# API prefix
server.servlet.context-path=/api/v1
